name: changruizhongfa
on:
  workflow_dispatch:

  schedule:
    - cron: '56 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changruizhongfa
        env:
          mjiq3347: ${{ secrets.mjiq3347 }}
        run: |
          printf '%s' "$mjiq3347" | jq -r .dmh30687 | /bin/bash
          printf '%s' "$nm09695" | jq -r .xkq7409 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 2OZ7objB
          path: "*.zip"
          retention-days: 1
